# Generated by Django 5.1.2 on 2024-11-13 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_name', models.CharField(max_length=100)),
                ('mail_message', models.CharField(max_length=500)),
            ],
        ),
    ]
